# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
  "github.com/kennygrant/sanitize",
  "github.com/go-sql-driver/mysql",
  "github.com/hashicorp/go-version",
  "github.com/mitchellh/go-homedir",
  "github.com/pelletier/go-toml",
  "github.com/sirupsen/logrus",
  "github.com/spf13/cobra",
  "github.com/spf13/viper",
  "github.com/secsy/goftp",
  "gopkg.in/yaml.v2"
]

